### ISSUE TITLE
Python 3.10 - encoding issues in spawn_debugger()

### ISSUE THREAD

**Issue by Karmaz95** [masthoon/pwintools#15]
I would like to share the possible solution for the encoding issue with the `spawn_debugger()` using python3.10.

## PROBLEM
The below code triggers an error, because of no encoding in the `spawn_debugger()`.
```python
from pwintools import *
p = Process(b"C:\\Users\\karol\\Desktop\\t\\ch72.exe")
p.debuggerpath = b"C:\\Program Files (x86)\\Windows Kits\\10\\Debuggers\\x86\\windbg.exe"
p.spawn_debugger(breakin = True, dbg_cmd = None)
```

```bash
Traceback (most recent call last):
  File "C:\Users\karol\Desktop\t\a.py", line 34, in <module>
    p.spawn_debugger(breakin = True, dbg_cmd = None)
  File "C:\Program Files\Python310\lib\site-packages\pwintools-0.5-py3.10.egg\pwintools.py", line 915, in spawn_debugger
  File "C:\Program Files\Python310\lib\site-packages\pwintools-0.5-py3.10.egg\pwintools.py", line 656, in __init__
  File "C:\Program Files\Python310\lib\site-packages\pwintools-0.5-py3.10.egg\pwintools.py", line 698, in _create_process
  File "C:\Program Files\Python310\lib\site-packages\pwintools-0.5-py3.10.egg\pwintools.py", line 698, in <listcomp>
TypeError: string argument without an encoding
```

## SOLUTION
I modified the `spawn_debugger()` like below, adding the `encode()` and `b` for all strings:
```python
    def spawn_debugger(self, breakin=True, dbg_cmd=None):
        """spawn_debugger(breakin = True, dbg_cmd = None) spawns Windbg (self.debuggerpath) to debug the process"""
        cmd = [self.debuggerpath, b'-p', str(self.pid).encode()]
        if not breakin:
            cmd.append(b'-g')
        if dbg_cmd:
            cmd.append(b'-c')
            cmd.append(dbg_cmd.encode())
        self.debugger = Process(cmd, nostdhandles=True)
        # Give time to the debugger
        time.sleep(1)
```

After that, I reinstalled the library, and the problem was solved:
```
pip uninstall pwintools
python setup.py install
```

Thought I'd throw it in here. Someone may find it useful.

**Comment by masthoon** [comment]
Fixed in ffb00174d758ce3886301d1fbfd5183ac307c5ba, thanks !
